# Generated by Django 3.2.8 on 2021-10-31 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('deductionID', models.IntegerField(primary_key=True, serialize=False)),
                ('AmountOfMoney', models.IntegerField()),
                ('Reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentID', models.IntegerField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.department')),
            ],
        ),
        migrations.CreateModel(
            name='Overload',
            fields=[
                ('overloadID', models.IntegerField(primary_key=True, serialize=False)),
                ('AmountOfMoney', models.IntegerField()),
                ('Reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salaryID', models.IntegerField(primary_key=True, serialize=False)),
                ('TotalMoney', models.IntegerField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleID', models.IntegerField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=50)),
                ('base_salary', models.IntegerField()),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.department')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.role'),
        ),
    ]
