# Generated by Django 3.2.8 on 2021-11-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='departmentID',
        ),
    ]
