# Generated by Django 3.2.8 on 2021-11-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_getdeductionfine_getoverloadpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getoverloadpayment',
            name='employeeID',
        ),
        migrations.RemoveField(
            model_name='getoverloadpayment',
            name='overloadID',
        ),
        migrations.DeleteModel(
            name='GetDeductionFine',
        ),
        migrations.DeleteModel(
            name='GetOverloadPayment',
        ),
    ]
